version: "3.2"

services:

  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
      - frontend
    ports:
      - "81:80"
    volumes:
      - ./opencart/:/var/www/html/
    container_name: "${PHP_NAME}"

  
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "${MARIADB_NAME}"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    networks:
      - backend
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    container_name: "${ADMINER_NAME}"

networks:
  backend:
  frontend: