ARG PHP_VERSION=""
FROM php:${PHP_VERSION}-apache

# RUN apt-get update; \
#     apt-get upgrade;

#RUN docker-php-ext-install mysqli
#RUN docker-php-ext-install pdo pdo_mysql

# RUN sed -i "s/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/" /etc/apache2/conf/httpd.conf;

# # COPY .bashrc /root/.bashrc

# # Copy apache vhost file to proxy php requests to php-fpm container
# COPY demo.apache.conf /etc/apache2/conf/demo.apache.conf
# RUN echo "Include /etc/apache2/conf/demo.apache.conf" \
#     >> /etc/apache2/conf/httpd.conf